import webscraper as ws
import imagegen as img
import io
from PIL import Image
import tweepy
from datetime import datetime

from twitter_key import (
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)

webscraper = ws.Webscraper(safe_mode=True)
caption_with_tags = webscraper.generate_prompt()
start_tag, end_tag = '<caption>', '</caption>'
caption_text = 'What Does Today Look Like? #wdtll\n\n' + caption_with_tags.split(start_tag)[1].split(end_tag)[0] + '\n\n(autogenerated image)'

print('Caption: ' + caption_text)

image_gen = img.ImageGen()
image_bytes = image_gen.query('Cartoon style painting: ' + caption_text)
image = Image.open(io.BytesIO(image_bytes))
image.show()

# Save image in-memory
b = io.BytesIO()
current_date = datetime.now().strftime("%Y-%m-%d")
file_name = 'wdtll-' + current_date
image.save(b, "PNG")
b.seek(0)

auth = tweepy.OAuthHandler(consumer_key=consumer_key, consumer_secret=consumer_secret)
auth.set_access_token(key=access_token, secret=access_token_secret)
api = tweepy.API(auth)

# Upload media to Twitter APIv1.1
ret = api.media_upload(filename=file_name, file=b)

# create APIv2 client
client = tweepy.Client(
    consumer_key=consumer_key,
    consumer_secret=consumer_secret,
    access_token=access_token,
    access_token_secret=access_token_secret
)

client.create_tweet(media_ids=[ret.media_id_string], text=caption_text)
